name: Eco Hair Color Style
favicon: null
layout_spectrum: 0.9078947
typography_spectrum: 0.42989
title: Eco Hair Color Style
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad9b3'
    - '#4f74b8'
    - '#532700'
    - '#cad011'
    - '#24bf28'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
