title: Eco Hair Color Style
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.7951128
  lightness: 0.6278195
  brandColors:
    - '#FAF4D0'
    - '#425CA3'
    - '#5D5C4B'
    - '#9ABDFF'
    - '#3B1F02'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Eco Hair Color Style
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4548872
layout_spectrum: 0.8477443
