title: Eco Hair Color Style
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.75
  rhythmicContrast: 0.5
  brandColors:
    - '#dad9b3'
    - '#ffffff'
    - '#552700'
    - '#54b629'
    - '#4b70bd'
  lightness: 0.5625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Eco Hair Color Style
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.44672
layout_spectrum: 0.8823178
